spring:
  profiles:
    active: k8s
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    url: jdbc:postgresql://reflecta-postgres:5432/reflecta
    username: reflecta
    password: reflecta
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org.springframework: INFO

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
