version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reflecta-postgres
    environment:
      POSTGRES_DB: reflecta
      POSTGRES_USER: reflecta
      POSTGRES_PASSWORD: reflecta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U reflecta" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reflecta-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reflecta
      SPRING_DATASOURCE_USERNAME: reflecta
      SPRING_DATASOURCE_PASSWORD: reflecta
      JAVA_TOOL_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8787:8787"

volumes:
  pgdata: