apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflecta-postgres
  namespace: reflecta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reflecta-postgres
  template:
    metadata:
      labels:
        app: reflecta-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: reflecta
            - name: POSTGRES_USER
              value: reflecta
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reflecta-secrets
                  key: db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: reflecta-postgres-pvc
