apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reflecta-postgres-pvc
  namespace: reflecta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
