apiVersion: v1
kind: Service
metadata:
  name: reflecta-app
  namespace: reflecta
spec:
  selector:
    app: reflecta-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
